services:
  caddy:
    image: ghcr.io/vqvu/caddy-custom:latest
    build: . # If you want build locally using docker-compose
    restart: unless-stopped
    environment:
      - CF_API_TOKEN=changeme
    cap_drop:
      - ALL
    cap_add:
      - NET_ADMIN
      - NET_BIND_SERVICE # If binding to ports <1024
    ports:
      - 80:80
      - 443:443
      - 443:443/udp
    volumes:
      - $PWD/Caddyfile:/etc/caddy/Caddyfile
      - $PWD/site:/srv
      - caddy_data:/data
      - caddy_config:/config

volumes:
  caddy_data:
  caddy_config:
